name: wagtrack
description: ":3"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  cloud_firestore: ^4.17.5
  firebase_auth: ^4.19.5
  firebase_core: ^2.31.0
  firebase_storage: ^11.7.7
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^7.0.0
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  image_picker: ^1.1.2
  path: ^1.9.0
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  flutter_launcher_icons: "^0.13.1"
  flutter_datetime_picker_plus: ^2.2.0
  intl: ^0.19.0
  logger: ^2.3.0
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.3
  mocktail: ^1.0.0
  get_it: ^7.7.0
  flutter_native_splash: ^2.4.0

# Config for Flutter launcher icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/wagtrack.png"
  min_sdk_android: 23

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/

# config for splash screen
# https://pub.dev/packages/flutter_native_splash
flutter_native_splash:
  android: true
  ios: true
  web: false
  image: assets/splash-logo.png
  color: "#FFFFFF"
  android_12:
    image: assets/splash-logo.png
    color: "#FFFFFF"