name: Dart-Main

on:
  workflow_dispatch:
  # push:
  #   branches: 
  #     - dev
  # pull_request:
  #   branches: 
  #     - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter --version

      - name: Install dependencies
        run: dart pub get

      # Upgrade flutter
      - run: flutter upgrade
      
      # Get flutter dependencies.
      - run: flutter pub get
      
      # Statically analyze the Dart code for any errors.
      - name: Analyze project source
        run: dart analyze --fatal-infos

      # - name: Run tests
      #   run: flutter test
