name: Flutter Build CI

# This workflow is triggered on pushes to the repository.
# runs when pushed/merged (via pull request) into main

on:
  push:
    branches:
    - main
    
# on: push    # Default will running for every branch.
    
jobs:
  build:
    # This job will run on ubuntu virtual machine
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v4
    
    # Setup Java
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    # Setup the flutter environment.
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable' # 'dev', 'alpha', default to: 'stable'
        # flutter-version: '1.12.x' # you can also specify exact version of flutter
    
    # Upgrade flutter
    - run: flutter upgrade

    # Run flutter doctor to show information about the toolchain for debug purposes.
    - run: flutter doctor -v
    
    # Get flutter dependencies.
    - run: flutter pub get
    
    # Statically analyze the Dart code for any errors.
    - run: flutter analyze --no-fatal-infos --no-fatal-warnings
    
    # Run widget tests for our flutter project.
    # - run: flutter test
    
    # Build apk.
    - run: flutter build apk
    
    # Upload generated apk to the artifacts.
    - uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: build/app/outputs/apk/release/app-release.apk
