name: Flutter Build and Test CI
# Automatically runs tests, builds apk, then uploads apk to Github artifacts

# This workflow is triggered on pushes and pull requests to `dev`
on:
  push:
    branches:
    - dev
  pull_request:
    branches:
    - dev
    
jobs:
  build:
    # This job will run on ubuntu virtual machine
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v4
    
    # Setup Java
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    
    # Setup the flutter environment.
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable' # 'dev', 'alpha', default to: 'stable'
        # flutter-version: '1.12.x' # you can also specify exact version of flutter
    
    # Upgrade flutter
    # I think the default Dart version is too old so you have to run this
    - run: flutter upgrade
    
    # Get flutter dependencies.
    - run: flutter pub get
    
    # Statically analyze the Dart code for any errors.
    # flags are to prevent fatally exiting on infos and warnings - which would stop the whole workflow
    - run: flutter analyze --no-fatal-infos --no-fatal-warnings
    
    # Run tests.
    - run: flutter test
    
    # Build apk.
    - run: flutter build apk
    
    # Upload generated apk to the artifacts.
    - uses: actions/upload-artifact@v4
      with:
        name: debug-apk
        path: build/app/outputs/apk/debug/app-debug.apk
